### ISSUE TITLE
Possible tools to add.

### ISSUE THREAD

**Issue by aleksandrenko** [LittleFurryBastards/webpack-babel-react#1]
There are a couple of possible tools to be added to this seed project:
- [ ] ~~Redux~~ (will be moved to another task/issue)
- [ ] ~~Immutable-js~~ (if used will be introduces with Redux)
- [ ] ~~Flow (no windows support)~~
- [x] SASS/LESS support
- [x] git-hooks (sharable for all cloned project) - Hooks to run linters and test before comiting and/or pushing.
- [x] react-router

**Comment by aleksandrenko** [comment]
- react-router

**Comment by lostm1nd** [comment]
All in good time; )

**Comment by kazandjiev** [comment]
We can even maybe add them in different branches so that you can pick and choose what you need on top of your base seed. In every branch will be an explanation how to add the specific tool to the base setup or you can even merge cherry-pick commits and you will be good to go . Something like a primitive customize option of some sort.

**Comment by lostm1nd** [comment]
React router is now part of the package ; )

**Comment by aleksandrenko** [comment]
+ git-hooks (sharable for all cloned project) - Hooks to run linters and test before comiting and/or pushing.

**Comment by Chariyski** [comment]
@aleksandrenko - https://github.com/maxhoffmann/captain-git-hook ;) 

Tested with Dido and it works perfect.

**Comment by aleksandrenko** [comment]
Nice. I will try to find the time to implement it.

**Comment by aleksandrenko** [comment]
I just made a push. Can anyone check it out, just to make sure is fine ...

**Comment by Chariyski** [comment]
This is the concept :P
